# train
CUDA_VISIBLE_DEVICES="0" python jailbreakGenSCAVIter.py --judge sjf --maxIter 20 --trainL 256 --layer -2 --model "PawanKrd/Meta-Llama-3-8B-Instruct" --saveDir ./iterSCAVWeight --softThres 0.05 0.6 --gpuLR --evalPT "min" --pt 0.5 --posi all --embType last --val
CUDA_VISIBLE_DEVICES="0" python jailbreakGenSCAVIter.py --judge sjf --maxIter 20 --trainL 256 --layer -2 --model 'meta-llama/Llama-2-7b-chat-hf' --saveDir ./iterSCAVWeight --softThres 0.05 0.6 --gpuLR --evalPT "min" --pt 0.5 --posi all --embType last --val
CUDA_VISIBLE_DEVICES="0" python jailbreakGenSCAVIter.py --judge sjf --maxIter 20 --trainL 256 --layer -2 --model "Qwen/Qwen3-4B-Instruct-2507" --saveDir ./iterSCAVWeight --softThres 0.05 0.6 --gpuLR --evalPT "min" --pt 0.5 --posi all --embType last --val
CUDA_VISIBLE_DEVICES="0" python jailbreakGenSCAVIter.py --judge sjf --maxIter 20 --trainL 256 --layer -2 --model "Qwen/Qwen2.5-14B-Instruct" --saveDir ./iterSCAVWeight --softThres 0.05 0.6 --gpuLR --evalPT "min" --pt 0.5 --posi all --embType last --val
CUDA_VISIBLE_DEVICES="0" python jailbreakGenSCAVIter.py --judge sjf --maxIter 20 --trainL 256 --layer -2 --model "lmsys/vicuna-7b-v1.5" --saveDir ./iterSCAVWeight --softThres 0.05 0.6 --gpuLR --evalPT "min" --pt 0.5 --posi all --embType last --val
CUDA_VISIBLE_DEVICES="0" python jailbreakGenSCAVIter.py --judge sjf --maxIter 20 --trainL 256 --layer -2 --model "mistralai/Mistral-7B-Instruct-v0.2" --saveDir ./iterSCAVWeight --softThres 0.05 0.6 --gpuLR --evalPT "min" --pt 0.5 --posi all --embType last --val
CUDA_VISIBLE_DEVICES="0" python jailbreakGenSCAVIter.py --judge sjf --maxIter 20 --trainL 256 --layer -2 --model "google/gemma-2-9b-it" --saveDir ./iterSCAVWeight --softThres 0.05 0.6 --gpuLR --evalPT "min" --pt 0.5 --posi all --embType last --val
# eval
CUDA_VISIBLE_DEVICES="4" python evalMy.py --evalData harm --model "PawanKrd/Meta-Llama-3-8B-Instruct" --evalPT "min" --clfP "./iterSCAVWeight/PawanKrd_Meta-Llama-3-8B-Instruct/harm[50, 50]_benign[50, 50]/judgesjf_embTypelast_posiall_filterDataFalse_layer[-32, -2]_penaltyl2_gpuLRTrue_reweightFalse_maxIter20_trainL256_pt0.5_softThres[0.05, 0.6]_clfrs.pt" --csvP myRes_general.csv --evalClfr 'best' --layer -2 --posi 'all' --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="4" python evalMy.py --evalData harm --model 'meta-llama/Llama-2-7b-chat-hf' --evalPT "min" --clfP "./iterSCAVWeight/meta-llama_Llama-2-7b-chat-hf/harm[50, 50]_benign[50, 50]/judgesjf_embTypelast_posiall_filterDataFalse_layer[-32, -2]_penaltyl2_gpuLRTrue_reweightFalse_maxIter20_trainL256_pt0.5_softThres[0.05, 0.6]_clfrs.pt" --csvP myRes_general.csv --evalClfr 'best' --layer -2 --posi 'all' --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="4" python evalMy.py --evalData harm --model "Qwen/Qwen3-4B-Instruct-2507" --evalPT "min" --clfP "./iterSCAVWeight/Qwen_Qwen3-4B-Instruct-2507/harm[50, 50]_benign[50, 50]/judgesjf_embTypelast_posiall_filterDataFalse_layer[-36, -2]_penaltyl2_gpuLRTrue_reweightFalse_maxIter20_trainL256_pt0.5_softThres[0.05, 0.6]_clfrs.pt" --csvP myRes_general.csv --evalClfr 'best' --layer -2 --posi 'all' --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="4" python evalMy.py --evalData harm --model "Qwen/Qwen2.5-14B-Instruct" --evalPT "min" --clfP "./iterSCAVWeight/Qwen_Qwen2.5-14B-Instruct/harm[50, 50]_benign[50, 50]/judgesjf_embTypelast_posiall_filterDataFalse_layer[-48, -2]_penaltyl2_gpuLRTrue_reweightFalse_maxIter20_trainL256_pt0.5_softThres[0.05, 0.6]_clfrs.pt" --csvP myRes_general.csv --evalClfr 'best' --layer -2 --posi 'all' --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="4" python evalMy.py --evalData harm --model "lmsys/vicuna-7b-v1.5"  --evalPT "min" --clfP "./iterSCAVWeight/lmsys_vicuna-7b-v1.5/harm[50, 50]_benign[50, 50]/judgesjf_embTypelast_posiall_filterDataFalse_layer[-32, -2]_penaltyl2_gpuLRTrue_reweightFalse_maxIter20_trainL256_pt0.5_softThres[0.05, 0.6]_clfrs.pt" --csvP myRes_general.csv --evalClfr 'best' --layer -2 --posi 'all' --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="4" python evalMy.py --evalData harm --model "mistralai/Mistral-7B-Instruct-v0.2" --evalPT "min" --clfP "./iterSCAVWeight/mistralai_Mistral-7B-Instruct-v0.2/harm[50, 50]_benign[50, 50]/judgesjf_embTypelast_posiall_filterDataFalse_layer[-32, -2]_penaltyl2_gpuLRTrue_reweightFalse_maxIter20_trainL256_pt0.5_softThres[0.05, 0.6]_clfrs.pt" --csvP myRes_general.csv --evalClfr 'best' --layer -2 --posi 'all' --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="4" python evalMy.py --evalData harm --model "google/gemma-2-9b-it" --evalPT "min" --clfP "./iterSCAVWeight/google_gemma-2-9b-it/harm[50, 50]_benign[50, 50]/judgesjf_embTypelast_posiall_filterDataFalse_layer[-42, -2]_penaltyl2_gpuLRTrue_reweightFalse_maxIter20_trainL256_pt0.5_softThres[0.05, 0.6]_clfrs.pt" --csvP myRes_general.csv --evalClfr 'best' --layer -2 --posi 'all' --evalJudge "sjf" "hb" "model base_url api_key"