# SCAV
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method scav --strength 1e-4 --trainsize 0.1 --model "PawanKrd/Meta-Llama-3-8B-Instruct" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method scav --strength 1e-4 --trainsize 0.1 --model 'meta-llama/Llama-2-7b-chat-hf' --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method scav --strength 1e-4 --trainsize 0.1 --model "Qwen/Qwen3-4B-Instruct-2507" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method scav --strength 1e-4 --trainsize 0.1 --model "Qwen/Qwen2.5-14B-Instruct" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method scav --strength 1e-4 --trainsize 0.1 --model "lmsys/vicuna-7b-v1.5" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method scav --strength 1e-4 --trainsize 0.1 --model "mistralai/Mistral-7B-Instruct-v0.2" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method scav --strength 1e-4 --trainsize 0.1 --model "google/gemma-2-9b-it" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
# rep
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method rep --strength 1.0 --trainsize 1.0 --model "PawanKrd/Meta-Llama-3-8B-Instruct" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method rep --strength 1.0 --trainsize 1.0 --model 'meta-llama/Llama-2-7b-chat-hf' --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="4" python otherBaseline.py --evalData harm --method rep --strength 1.0 --trainsize 1.0 --model "Qwen/Qwen3-4B-Instruct-2507" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method rep --strength 1.0 --trainsize 1.0 --model "Qwen/Qwen2.5-14B-Instruct" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method rep --strength 1.0 --trainsize 1.0 --model "lmsys/vicuna-7b-v1.5" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method rep --strength 1.0 --trainsize 1.0 --model "mistralai/Mistral-7B-Instruct-v0.2" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="1" python otherBaseline.py --evalData harm --method rep --strength 1.0 --trainsize 1.0 --model "google/gemma-2-9b-it" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
# rd
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method rd --trainsize 0.8 --model "PawanKrd/Meta-Llama-3-8B-Instruct" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method rd --trainsize 0.8 --model 'meta-llama/Llama-2-7b-chat-hf' --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method rd --trainsize 0.8 --model "Qwen/Qwen3-4B-Instruct-2507" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method rd --trainsize 0.8 --model "Qwen/Qwen2.5-14B-Instruct" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method rd --trainsize 0.8 --model "lmsys/vicuna-7b-v1.5" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method rd --trainsize 0.8 --model "mistralai/Mistral-7B-Instruct-v0.2" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method rd --trainsize 0.8 --model "google/gemma-2-9b-it" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
# angular
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method angular --trainsize 1.0 --model "PawanKrd/Meta-Llama-3-8B-Instruct" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method angular --trainsize 1.0 --model 'meta-llama/Llama-2-7b-chat-hf' --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method angular --trainsize 1.0 --model "Qwen/Qwen3-4B-Instruct-2507" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method angular --trainsize 1.0 --model "Qwen/Qwen2.5-14B-Instruct" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method angular --trainsize 1.0 --model "lmsys/vicuna-7b-v1.5" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method angular --trainsize 1.0 --model "mistralai/Mistral-7B-Instruct-v0.2" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
CUDA_VISIBLE_DEVICES="2" python otherBaseline.py --evalData harm --method angular --trainsize 1.0 --model "google/gemma-2-9b-it" --csvP ./otherBaselineRes_general.csv --evalJudge "sjf" "hb" "model base_url api_key"
